### ISSUE TITLE
IgcPivotDataSelector - Cannot re-select data after all rows, columns and values are deselected.

### ISSUE THREAD

**Issue by norikois** [IgniteUI/igniteui-webcomponents#1010]
## Description  
IgcPivotDataSelector - Cannot re-select data after all rows, columns and values are deselected.

## Steps to reproduce  

1. Start the attached reproducible sample.
2. In the pivot data selector, deselect "column1".
3. Deselect "Sum".
4. Select "column5".

## Result  
Type errors occurs.
Users can never select rows, columns or values.

ERROR TypeError: Cannot read properties of undefined (reading 'dimensionValues')
at t2.extractFromDimension (combined.js:46164:39)
x twice

ERROR TypeError: Cannot read properties of undefined (reading 'headerGroupClasses')
at template (combined.js:46183:693)
x twice

## Expected result  
No type error occurs.
Users can select rows, columns and values again.

## Attachments  
[c-00234067-igc-pivot-grid.zip](https://github.com/IgniteUI/igniteui-webcomponents/files/13711343/c-00234067-igc-pivot-grid.zip)

**Comment by norikois** [comment]
This might be duplicated with https://github.com/IgniteUI/igniteui-webcomponents/issues/953, but the steps to reproduce are different and another type error about headerGroupClasses occurs in this case, so I submitted this issue separately.
